# 02 — 量表/构念汇总

当前问卷文件是汇总导出，不是逐名参与者作答矩阵。因此 Cronbach's alpha、McDonald's omega 和个体层面的量表总分不能从该文件计算。本 notebook 报告可由汇总数据支持的题项均值、构念均值和高分段比例。

In [1]:
import sys
from pathlib import Path

ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(ROOT))

import pandas as pd
pd.set_option("display.max_colwidth", 120)

In [2]:
from src.data_loader import parse_survey_export
from src.preprocessing import attach_slider_constructs, construct_mean_summary
from src.analysis import slider_bin_agreement

parsed = parse_survey_export(ROOT / "data" / "问卷原始数据.xlsx")
sliders = attach_slider_constructs(parsed["sliders"])
agreement = slider_bin_agreement(parsed["options"]).merge(
    sliders[["q_num", "short_label", "construct", "mean"]],
    on="q_num",
    how="left",
)
constructs = construct_mean_summary(parsed["sliders"])

## 1. 滑动条题项均值

In [3]:
display(sliders[["q_num", "short_label", "construct", "valid_n", "mean"]])

    q_num           short_label  construct  valid_n  mean
0      10             自由重量区不易接近  空间压迫/训练焦虑     32.0  3.19
1      11              男性较多时不自在  空间压迫/训练焦虑     32.0  4.24
2      12         镜子/公开可见增强被评价感  空间压迫/训练焦虑     32.0  3.57
3      13            担心动作不标准被评价  空间压迫/训练焦虑     32.0  3.81
4      14            自由重量区男性主导感  空间压迫/训练焦虑     32.0  3.61
5      15             拥挤感降低停留意愿  空间压迫/训练焦虑     32.0  3.88
6      21            审美内容影响运动选择   社交媒体审美内化     32.0  3.40
7      22            担心力量训练不够纤细   社交媒体审美内化     32.0  1.85
8      23          内化社交媒体女性身材标准   社交媒体审美内化     32.0  2.73
9      24           健身房训练目标自我效能     训练自我效能     32.0  3.49
10     25         减少刻板印象会提升参与意愿      干预接受度     32.0  3.39
11     26          半私密分区会提升使用意愿      干预接受度     32.0  4.04
12     27  女性初学者workshop会提升尝试意愿      干预接受度     32.0  4.50

## 2. 构念均值（题项均值的平均）

In [4]:
display(constructs)

,construct,items,item_count,mean,min_item_mean,max_item_mean,valid_n
0,干预接受度,"Q25, Q26, Q27",3,3.976667,3.39,4.50,32.0
1,社交媒体审美内化,"Q21, Q22, Q23",3,2.660000,1.85,3.40,32.0
2,空间压迫/训练焦虑,"Q10, Q11, Q12, Q13, Q14, Q15",6,3.716667,3.19,4.24,32.0
3,训练自我效能,Q24,1,3.490000,3.49,3.49,32.0

## 3. 高分段比例

高分段定义为平台导出的 3.5--4.2 与 4.3--5 两个分段之和。

In [5]:
display(agreement[["q_num", "short_label", "mean", "low_pct", "mid_pct", "high_pct"]])

    q_num           short_label  mean  low_pct  mid_pct  high_pct
0      10             自由重量区不易接近  3.19   25.000   34.375    40.625
1      11              男性较多时不自在  4.24    9.375    9.375    81.250
2      12         镜子/公开可见增强被评价感  3.57   21.875   25.000    53.125
3      13            担心动作不标准被评价  3.81   12.500   21.875    65.625
4      14            自由重量区男性主导感  3.61   15.625   21.875    62.500
5      15             拥挤感降低停留意愿  3.88   12.500   12.500    75.000
6      21            审美内容影响运动选择  3.40   21.875   18.750    59.375
7      22            担心力量训练不够纤细  1.85   81.250    3.125    15.625
8      23          内化社交媒体女性身材标准  2.73   43.750   25.000    31.250
9      24           健身房训练目标自我效能  3.49   18.750   31.250    50.000
10     25         减少刻板印象会提升参与意愿  3.39   18.750   31.250    50.000
11     26          半私密分区会提升使用意愿  4.04   15.625    3.125    81.250
12     27  女性初学者workshop会提升尝试意愿  4.50    0.000    3.125    96.875